<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Snowdog\Hyva\Checkout\PayU\Block\Script;

/** @var Script $viewModel */
/** @var Escaper $escaper */
/** @var Template $block */
$viewModel = $block->getViewModel();
?>
<script>
    'use strict';

    (function () {
        window.addEventListener('checkout:step:loaded', async event => {
            var form = document.getElementById('payment_payu_card_form');
            if (!form) {
                return;
            }
            let payuSDK;
            try {
                payuSDK = PayU(<?= $escaper->escapeJs($viewModel->getPosId()) ?>, true);
            } catch (e) {
                payuSDK = null
                console.log(e)
                return;
            }
            var secureFormOptions = {
                elementFormNumber: '#payu-card-number',
                elementFormDate: '#payu-card-date',
                elementFormCvv: '#payu-card-cvv',
                config: {
                    cardIcon: true,
                    placeholder: {
                        number: '',
                        cvv: ''
                    },
                    style: {
                        basic: {
                            fontSize: '18px',
                        }
                    },
                    lang: '<?= $escaper->escapeJs($viewModel->getLanguage()) ?>'
                }
            };
            const secureForms = payuSDK.secureForms();
            const secureFormNumber = secureForms.add('number', secureFormOptions.config);
            secureFormNumber.render(secureFormOptions.elementFormNumber);
            const secureFormDate = secureForms.add('date', secureFormOptions.config);
            secureFormDate.render(secureFormOptions.elementFormDate);
            const secureFormCvv = secureForms.add('cvv', secureFormOptions.config);
            secureFormCvv.render(secureFormOptions.elementFormCvv);

            hyvaCheckout.navigation.addTask((params) => {
                return payuSDK.tokenize('SINGLE').then( // TODO: tokenizer method based on checkbox
                    function (result) {
                        if (result.status === 'SUCCESS') {
                            console.log(result.body.token);
                            return Magewire.find('checkout.payment.method.payu_gateway_card').token(result.body.token).then(() => {
                                return true;
                            });
                        }
                        return false;
                    }
                );
            })


        }, {})
    })();
</script>
<script defer src="<?= $viewModel->getSDKUrl() ?>"></script>