<?php

declare(strict_types=1);

/** @var Template $block */
/** @var PayU $magewire */

/** @var Escaper $escaper */

use Snowdog\Hyva\Checkout\PayU\Payment\Method\PayU;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

?>


<div class="grid grid-cols-5">
    <?php foreach ($magewire->methods as $method): ?>
        <button type="button"
                class="w-36 h-12 m-2 p-2 bg-contain bg-center bg-no-repeat hover:bg-container-darker <?php if ($method['value'] == $magewire->method): ?>border-2<?php endif ?>"
                wire:click="$set('method', '<?= $method['value'] ?>')"
                style="background-image: url('<?= $method['brandImageUrl'] ?>')" title="<?= $method['name'] ?>"
        >
        </button>
    <?php endforeach ?>
</div>