<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Payu\PaymentGateway\Block\Account\StoredCards;

/** @var StoredCards $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<?php
$storedCards = $this->getStoredCards();
?>
    <h2 id="my-cards-title" class="text-2xl mb-6"><?= $escaper->escapeHtml(__('Stored cards')) ?></h2>
<?php if ($storedCards && count($storedCards) > 0): ?>
    <div
            role="table"
            class="card mb-4"
            aria-labelledby="my-cards-title"
    >
        <div
                role="row"
                id="my-cards-table"
                class="grid grid-cols-3"
        >
            <div
                    role="columnheader"
                    class="text-sm text-secondary p-2"
            >
                <?= $escaper->escapeHtml(__('Card Number')) ?>
            </div>
            <div
                    role="columnheader"
                    class="text-sm text-secondary p-2"
            >
                <?= $escaper->escapeHtml(__('Card Expiration')) ?>
            </div>
            <div
                    role="columnheader"
                    class="text-sm text-secondary p-2 text-center"
            >
                <?= $escaper->escapeHtml(__('Action')) ?>
            </div>
        </div>
        <?php $i = 0; ?>
        <?php foreach ($storedCards as $card): ?>
            <?php $i++; ?>
            <div
                    role="row"
                    class="grid grid-cols-3"
            >
                <div
                        role="rowheader"
                        class="p-2 flex items-center <?= $i % 2 === 0 ? '' : ' bg-container-darker' ?>"
                >
                    <div class="w-12 h-4 m-2 p-2 bg-no-repeat bg-center bg-contain" style="background-image: url('<?= $escaper->escapeHtml($card->brandImageUrl) ?>')"
                         title="<?= $escaper->escapeHtml($card->cardBrand); ?>"></div>
                    <?= $escaper->escapeHtml($card->cardNumberMasked); ?>
                </div>

                <div
                        role="cell"
                        class="p-2 flex items-center <?= $i % 2 === 0 ? '' : ' bg-container-darker' ?>"
                >
                    <?= $escaper->escapeHtml(
                        $card->cardExpirationMonth . '/' . $card->cardExpirationYear
                    ); ?>
                </div>

                <div
                        role="cell"
                        class="p-2 flex items-center justify-evenly<?= $i % 2 === 0 ? '' : ' bg-container-darker' ?>"
                >
                    <form
                            action="<?= $escaper->escapeUrl($block->getUrl('customer/account/deletestoredcard/')) ?>"
                            method="post"
                            class="inline-flex items-center"
                    >
                        <?= $block->getBlockHtml('formkey'); ?>
                        <input
                                type="hidden"
                                name="card_id"
                                value="<?= $escaper->escapeHtmlAttr($card->value) ?>"
                        />
                        <button
                                title="<?= $escaper->escapeHtmlAttr(__('Remove')) ?>"
                                type="submit"
                                class="inline-block text-sm underline text-secondary-darker"
                                aria-label="<?= $escaper->escapeHtmlAttr(
                                    __('Remove card') . ' ' . $card->cardBrand . ' ' . $card->cardNumberMasked,
                                    '0'
                                ) ?>"
                        >
                            <?= $heroicons->trashHtml('', 24, 24, ['aria-hidden' => 'true']) ?>
                        </button>
                    </form>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <div class="message info empty"><span><?= $escaper->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>